version:  "3"
services:

  db:
    build: mysql
    env_file: .env
    domainname: vcl.local
    hostname: db
    image: vcl-db
    volumes:
      - mysql_data:/var/lib/mysql
  
  web:
    build: web
    env_file: .env
    volumes:
      - web_logs:/var/log/apache2
      - ../vcl/web:/var/www/html
      - ../dev-conf:/etc/vcl-web-conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - db:db
    depends_on:
      - db
    domainname: vcl.local
    hostname: web
    image: vcl-web

  managementnode:
    build: managementnode
    env_file: .env
    volumes:
      - managementnode_logs:/var/log/vcl/
      - ../vcl/managementnode:/usr/local/vcl/
    links:
      - db:db
    depends_on:
      - db
    domainname: vcl.local
    hostname: managementnode
    image: vcl-managementnode

volumes:
  mysql_data:
  web_logs:
  managementnode_logs: