version:  "3.5"
services:

  db:
    build: mysql
    env_file: .env
    domainname: vcl.local
    hostname: db
    image: vcl-db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - database
  
  web:
    build: web
    env_file: .env
    volumes:
      - web_logs:/var/log/apache2
      - ../vcl/web:/var/www/html
      - ../dev-conf:/etc/vcl-web-conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - db:db
    depends_on:
      - db
    domainname: vcl.local
    hostname: web
    image: vcl-web
    networks:
      - frontend
      - database

  managementnode:
    build: managementnode
    env_file: .env
    volumes:
      - managementnode_logs:/var/log/vcl/
      - ../vcl/managementnode:/usr/local/vcl/
    links:
      - db:db
    depends_on:
      - db
    domainname: vcl.local
    hostname: managementnode
    image: vcl-managementnode
    networks:
      - database
      - vm_private

networks:
  frontend:
    name: vcl_frontend_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24        
  
  database:
    name: vcl_db_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.11.0/24
    
  vm_private:
    name: vcl_vm_private_net
    driver: bridge
    driver_opts:
      com.docker.network.parent: "ens224"
    ipam:
      driver: default
      config:
        - subnet: 172.16.12.0/24

volumes:
  mysql_data:
  web_logs:
  managementnode_logs: